name: Build Ubuntu Touch gta4l

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y repo git bc bison build-essential ccache curl flex g++-multilib gcc-multilib libssl-dev python3

      - name: Initialize Halium Sources
        run: |
          mkdir -p halium
          cd halium
          repo init -u https://github.com/Halium/android -b halium-11.0 --depth=1 -q
          mkdir -p .repo/local_manifests
          cp $GITHUB_WORKSPACE/local_manifest.xml .repo/local_manifests/gta4l.xml || echo "Manifest copy failed!"
          repo sync -c -j4 --force-sync --no-tags -q

      - name: Build halium-boot
        run: |
          cd halium
          source build/envsetup.sh
          breakfast gta4l || lunch halium_gta4l-userdebug
          mka halium-boot -j3 2>&1 | tee build.log

      - name: Upload halium-boot
        uses: actions/upload-artifact@v4
        with:
          name: halium-boot-gta4l
          path: halium/out/target/product/gta4l/halium-boot.img
